# frozen_string_literal: true

source "https://rubygems.org"

gem "activesupport"
gem "bundler"
gem "chunky_png"
gem "debug"
# gem "faraday"
gem "gem-ctags"
gem "guard"
gem "guard-bundler"
gem "guard-minitest"
gem "guard-rubocop"
gem "libnotify"
gem "matplotlib"
gem "minitest", "~> 5.15"
gem "minitest-reporters"
gem "mocha"
# gem "numo-narray"
gem "rainbow"
gem "rake"
gem "rubocop"
gem "rubocop-minitest"
gem "rubocop-performance"
gem "rubocop-rake"
gem "ruby-vips"
gem "torch-rb"
gem "tty-logger"
gem "tty-table", "~> 0.12"
